### ISSUE TITLE
ссылка на скачку не работает

### ISSUE THREAD

**Issue by cprkv** [kirill670/GTAV_SOURCE#3]
ссылка на скачку не работает. пишет 403 Forbidden

**Comment by kirill670** [comment]
![image](https://github.com/kirill670/GTAV_SOURCE/assets/51964569/8664c996-f37f-4947-bdeb-4950ac34bcc3)
Everything works for me, I'll check again later.

**Comment by kirill670** [comment]
Oh, sorry, 403)

**Comment by kirill670** [comment]
I'm uploading to Google Drive.
